from pathlib import Path
from typing import Dict, Any, List
from agents.base_agent import BaseAgent
from tools.file_ops import file_tools
from config import PROJECTS_DIR

class CoderAgent(BaseAgent):
    """
    Coder Agent: Writes, refactors, and organizes source code for user projects
    in UltronProjects/<project_name>/.
    """

    def __init__(self):
        super().__init__(
            name="Coder",
            role_description="Expert software engineer capable of writing clean, working applications."
        )

    def develop_project(self, project_name: str, requirements: str) -> Dict[str, Any]:
        """
        Creates a complete multi-file project based on user specifications.
        """
        clean_name = "".join(c for c in project_name if c.isalnum() or c in ("-", "_")).strip() or "NewProject"
        project_dir = PROJECTS_DIR / clean_name
        project_dir.mkdir(parents=True, exist_ok=True)

        system_prompt = (
            "You are the Coder Agent of Ultron. Your job is to generate full, working, production-grade source code.\n"
            "Respond ONLY with a JSON object containing the files to create, where keys are relative file paths and values are full code contents.\n"
            "Format:\n"
            "{\n"
            '  "files": {\n'
            '    "index.html": "<!DOCTYPE html>...",\n'
            '    "styles.css": "body { ... }",\n'
            '    "script.js": "// code...",\n'
            '    "README.md": "# Project Title..."\n'
            "  },\n"
            '  "summary": "Brief summary of what was implemented"\n'
            "}"
        )

        user_prompt = f"Project: {clean_name}\nRequirements: {requirements}\nDirectory: {project_dir}"

        raw_response = self.llm.complete(system_prompt, user_prompt, temperature=0.2, json_mode=True)
        parsed = self.parse_json(raw_response)

        created_files = []
        files_dict = parsed.get("files", {})

        if not files_dict:
            # Fallback code generation if in offline mock mode
            files_dict = self._generate_fallback_files(clean_name, requirements)

        for rel_path, content in files_dict.items():
            full_path = project_dir / rel_path
            write_res = file_tools.write_file(str(full_path), content)
            if write_res.get("success"):
                created_files.append(str(full_path))

        self.log(
            action="PROJECT_DEVELOPED",
            target=clean_name,
            details={"files_created": len(created_files), "project_dir": str(project_dir)}
        )

        return {
            "success": True,
            "project_name": clean_name,
            "project_dir": str(project_dir),
            "files": created_files,
            "summary": parsed.get("summary", f"Successfully developed {clean_name}")
        }

    def _generate_fallback_files(self, project_name: str, requirements: str) -> Dict[str, str]:
        """Provides default scaffold if no LLM key is configured."""
        if "website" in requirements.lower() or "landing page" in requirements.lower() or "agency" in requirements.lower():
            return {
                "index.html": (
                    "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
                    "  <meta charset=\"UTF-8\" />\n  <title>Digital Agency</title>\n"
                    "  <link rel=\"stylesheet\" href=\"styles.css\" />\n</head>\n<body>\n"
                    "  <header><h1>Elite Digital Marketing</h1><p>Data-Driven Growth</p></header>\n"
                    "  <main><button onclick=\"alert('Contact us today!')\">Get Started</button></main>\n"
                    "</body>\n</html>"
                ),
                "styles.css": (
                    "body { font-family: sans-serif; background: #0f172a; color: #f8fafc; text-align: center; padding: 50px; }\n"
                    "header { margin-bottom: 40px; }\n"
                    "button { background: #3b82f6; color: white; padding: 12px 24px; border: none; border-radius: 8px; cursor: pointer; font-size: 16px; }"
                ),
                "README.md": f"# {project_name}\nCreated automatically by Ultron Coder Agent.\nOpen index.html in any browser."
            }
        else:
            return {
                "main.py": (
                    "# Auto-generated by Ultron Coder Agent\n"
                    f"# Requirement: {requirements}\n\n"
                    "def main():\n"
                    "    print('Ultron project executed successfully!')\n\n"
                    "if __name__ == '__main__':\n"
                    "    main()\n"
                ),
                "README.md": f"# {project_name}\nPython utility script created by Ultron."
            }

coder_agent = CoderAgent()
