import asyncio
from typing import Dict, Any
from agents.base_agent import BaseAgent
from tools.app_control import app_tools
from tools.browser_control import browser_tools
from tools.file_ops import file_tools
from tools.shell_control import shell_tools
from tools.vpn_control import vpn_tools
from tools.api_gateway import api_gateway
from tools.safety_sentinel import safety_sentinel
from tools.system_telemetry import system_telemetry
from tools.vision_control import vision_control
from tools.memory_bank import memory_bank
from tools.doc_writer import doc_writer

class ExecutorAgent(BaseAgent):
    """
    Executor Agent: Dispatches physical OS actions, terminal scripts,
    browser commands, VPN switches, and external API requests.
    """

    def __init__(self):
        super().__init__(
            name="Executor",
            role_description="Direct system operator with full OS execution capabilities."
        )

    def execute_step(self, action: str, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes an individual action step generated by the Thinker/Manager.
        """
        action_clean = action.lower().strip()
        self.log("EXECUTE_STEP_START", target=action_clean, details=parameters)

        try:
            # 1. Application Control
            if action_clean in ("open_app", "launch_app"):
                app_name = parameters.get("app_name") or parameters.get("target") or ""
                return app_tools.open_app(app_name)

            elif action_clean in ("close_app", "kill_app"):
                app_name = parameters.get("app_name") or parameters.get("target") or ""
                return app_tools.close_app(app_name)

            # 2. Browser Navigation
            elif action_clean in ("open_url", "navigate", "browser"):
                url = parameters.get("url") or parameters.get("target") or "https://google.com"
                return browser_tools.open_url_quick(url)

            # 3. VPN Operations
            elif action_clean in ("connect_vpn", "vpn"):
                country = parameters.get("country") or parameters.get("target") or "Germany"
                return vpn_tools.connect(country)

            elif action_clean in ("disconnect_vpn",):
                return vpn_tools.disconnect()

            # 4. File Operations
            elif action_clean in ("create_directory", "mkdir", "create_folder"):
                path = parameters.get("path") or parameters.get("target") or ""
                return file_tools.create_directory(path)

            elif action_clean in ("write_file", "create_file"):
                path = parameters.get("path") or parameters.get("target") or ""
                content = parameters.get("content", "")
                return file_tools.write_file(path, content)

            elif action_clean in ("delete_path", "delete_file", "delete_folder"):
                path = parameters.get("path") or parameters.get("target") or ""
                return file_tools.delete_path(path)

            elif action_clean in ("move_file", "rename_file"):
                src = parameters.get("source") or parameters.get("src") or ""
                dst = parameters.get("destination") or parameters.get("dst") or ""
                return file_tools.move_file(src, dst)

            # 5. Shell Execution
            elif action_clean in ("execute_command", "shell", "run_terminal"):
                cmd = parameters.get("command") or parameters.get("target") or ""
                cwd = parameters.get("cwd")
                return shell_tools.execute_command(cmd, cwd=cwd)

            # 6. External APIs
            elif action_clean in ("send_email", "email"):
                return api_gateway.send_email(
                    to_email=parameters.get("to", ""),
                    subject=parameters.get("subject", ""),
                    body=parameters.get("body", "")
                )

            elif action_clean in ("post_instagram", "post_to_instagram"):
                return api_gateway.post_to_instagram(
                    image_path=parameters.get("image_path", ""),
                    caption=parameters.get("caption", "")
                )

            elif action_clean in ("create_ad_campaign", "facebook_ad"):
                return api_gateway.create_facebook_ad_campaign(
                    budget_amount=float(parameters.get("budget", 500)),
                    target_audience=parameters.get("target", "General"),
                    creative_text=parameters.get("creative", "")
                )

            elif action_clean in ("make_call", "phone_call"):
                return api_gateway.make_call(
                    phone_number=parameters.get("phone_number", ""),
                    instructions_or_script=parameters.get("script", "")
                )

            elif action_clean in ("system_status", "system_vitals", "telemetry", "hardware_stats"):
                vitals = system_telemetry.get_system_vitals()
                summary = system_telemetry.format_speech_summary()
                return {"success": True, "vitals": vitals, "message": summary}

            elif action_clean in ("analyze_screen", "screen_vision", "inspect_screen", "screenshot"):
                question = parameters.get("question") or parameters.get("target") or "What is on my screen?"
                return vision_control.analyze_screen(question)

            elif action_clean in ("create_document", "write_document", "google_doc", "doc_write"):
                topic = parameters.get("topic") or parameters.get("title") or "Document"
                target = parameters.get("app_target") or parameters.get("target") or "google_docs"
                content = parameters.get("content") or parameters.get("text")
                folder = parameters.get("target_folder") or parameters.get("folder")
                return doc_writer.create_and_write(topic=topic, app_target=target, custom_text=content, target_folder=folder)

            elif action_clean in ("remember", "save_memory", "set_preference"):
                key = parameters.get("key", "preference")
                val = parameters.get("value", "")
                cat = parameters.get("category", "user_preference")
                return memory_bank.remember(key, val, category=cat)

            elif action_clean in ("set_chrome_profile", "set_personal_profile"):
                profile_arg = parameters.get("profile") or parameters.get("name") or "Default"
                return memory_bank.set_personal_chrome_profile(profile_arg)

            elif action_clean == "echo":
                return {"success": True, "message": parameters.get("message", "")}

            else:
                return {"success": False, "error": f"Unknown executor action: {action_clean}"}

        except Exception as e:
            self.log("EXECUTE_STEP_ERROR", target=action_clean, details=str(e), status="failed")
            return {"success": False, "error": str(e)}

executor_agent = ExecutorAgent()
